### ISSUE TITLE
just wondering if this is still being worked on

### ISSUE THREAD

**Issue by Skywalker8510** [rmobis/supershulkers#1]

**Comment by Skywalker8510** [comment]
@rmobis I was just wondering if this is still being maintained because I believe this is a great vanillaesque mod. I would love to help but I cant code. I can help test things out and find bugs.

**Comment by rmobis** [comment]
@Skywalker8510 Thank you for taking interest in the project, but I'm afraid I won't be able to regularly invest time in supershulkers right now. I'll probably eventually update it to 1.18 and some new stuff *might* come in every once in a while, but likely not much. I'd be glad to accept PRs or even have it forked, should anyone be up to it.
